language: go

os:
  - linux
  - osx

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

install:
  - echo "Skipping the default go get..."

script:
  - hack/coverage
  - go install -v github.com/frapposelli/wwhrd
  - wwhrd check

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/cover.out

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
